//<auto-generated/>
using Ginox.BlackCauldron.Books.Controllers.Books;
using Zenject;

namespace Ginox.BlackCauldron.Books.Views.Books
{
    public class VillageDoctorsRecipeBookView : ABookView
    {
        [Inject]
        private void Init(VillageDoctorsRecipeBookController viewModel)
        {
            base.Init(viewModel);
        }
    }
}
