
//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients
{
    public class BeaverTailViewModel : AIngredientViewModel
    {
        public BeaverTailViewModel(BeaverTail model) : base(model)
        {
        }
    }
}
