//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients
{
    public class CoalViewModel : AIngredientViewModel
    {
        public CoalViewModel(Coal model) : base(model)
        {
        }
    }
}
