//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients
{
    public class CoalPowderController : AIngredientViewModel
    {
        public CoalPowderController(CoalPowder model) : base(model)
        {
        }
    }
}
