//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients
{
    public class GroundBayLeafsViewModel : AIngredientViewModel
    {
        public GroundBayLeafsViewModel(GroundBayLeafs model) : base(model)
        {
        }
    }
}
