//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients
{
    public class GroundMintViewModel : AIngredientViewModel
    {
        public GroundMintViewModel(GroundMint model) : base(model)
        {
        }
    }
}
