//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients
{
    public class GroundCattailCobViewModel : AIngredientViewModel
    {
        public GroundCattailCobViewModel(GroundCattailCob model) : base(model)
        {
        }
    }
}
