//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients
{
    public class GroundLicoriceRootViewModel : AIngredientViewModel
    {
        public GroundLicoriceRootViewModel(GroundLicoriceRoot model) : base(model)
        {
        }
    }
}
