//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients
{
    public class GroundHerringSkinViewModel : AIngredientViewModel
    {
        public GroundHerringSkinViewModel(GroundHerringSkin model) : base(model)
        {
        }
    }
}
