//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients
{
    public class GroundPineConeViewModel : AIngredientViewModel
    {
        public GroundPineConeViewModel(GroundPineCone model) : base(model)
        {
        }
    }
}
