//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients
{
    public class GroundFlyAgaricViewModel : AIngredientViewModel
    {
        public GroundFlyAgaricViewModel(GroundFlyAgaric model) : base(model)
        {
        }
    }
}
