
//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients
{
    public class MintViewModel : AIngredientViewModel
    {
        public MintViewModel(Mint model) : base(model)
        {
        }
    }
}
