//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class AbrasionsOintment : APotion
    {
        public AbrasionsOintment(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(AbrasionsOintment);
    }
}
