//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class AntiBaldnessLotion : APotion
    {
        public AntiBaldnessLotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(AntiBaldnessLotion);
    }
}
