//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class BeeCatalyst : APotion
    {
        public BeeCatalyst(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(BeeCatalyst);
    }
}
