//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class CalmingPotion : APotion
    {
        public CalmingPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(CalmingPotion);
    }
}
