//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class CharismaPotion : APotion
    {
        public CharismaPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(CharismaPotion);
    }
}
