//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class CharmPotion : APotion
    {
        public CharmPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(CharmPotion);
    }
}
