//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class CoughSyrup : APotion
    {
        public CoughSyrup(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(CoughSyrup);
    }
}
