//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class DeceptionProtectionPotion : APotion
    {
        public DeceptionProtectionPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(DeceptionProtectionPotion);
    }
}
