//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class DefencePotion : APotion
    {
        public DefencePotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(DefencePotion);
    }
}
