//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class HealingPotion : APotion
    {
        public HealingPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(HealingPotion);
    }
}
