//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class InspirationPotion : APotion
    {
        public InspirationPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(InspirationPotion);
    }
}
