//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class InvisibilityPotion : APotion
    {
        public InvisibilityPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(InvisibilityPotion);
    }
}
