//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class MasteryPotion : APotion
    {
        public MasteryPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(MasteryPotion);
    }
}
