//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class MemoryPotion : APotion
    {
        public MemoryPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(MemoryPotion);
    }
}
