//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class MentalClarityPotion : APotion
    {
        public MentalClarityPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(MentalClarityPotion);
    }
}
