//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class MindfulnessPotion : APotion
    {
        public MindfulnessPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(MindfulnessPotion);
    }
}
