//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class OblivionPotion : APotion
    {
        public OblivionPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(OblivionPotion);
    }
}
