//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class OintmentForRestoringLostFingers : APotion
    {
        public OintmentForRestoringLostFingers(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(OintmentForRestoringLostFingers);
    }
}
