//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class PerseverancePotion : APotion
    {
        public PerseverancePotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(PerseverancePotion);
    }
}
