//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class RejuvenationPotion : APotion
    {
        public RejuvenationPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(RejuvenationPotion);
    }
}
