//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class SpiritStrengtheningPotion : APotion
    {
        public SpiritStrengtheningPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(SpiritStrengtheningPotion);
    }
}
