//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class StaminaPotion : APotion
    {
        public StaminaPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(StaminaPotion);
    }
}
