//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class StealthPotion : APotion
    {
        public StealthPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(StealthPotion);
    }
}
