//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class StrengthPotion : APotion
    {
        public StrengthPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(StrengthPotion);
    }
}
