//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class StrongFertilizer : APotion
    {
        public StrongFertilizer(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(StrongFertilizer);
    }
}
