//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class ThickHairPotion : APotion
    {
        public ThickHairPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(ThickHairPotion);
    }
}
