//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class TinctureForRunnyNose : APotion
    {
        public TinctureForRunnyNose(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(TinctureForRunnyNose);
    }
}
