//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{
    public class WisdomPotion : APotion
    {
        public WisdomPotion(Material material) : base(material)
        {
        }

        public override string NameKey => nameof(WisdomPotion);
    }
}
