using Ginox.BlackCauldron.Core.Editor;
using System;
using UnityEditor;
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Editor
{
    public class CreatePotionWindow : EditorWindow
    {
        private static readonly string ALCHEMY_PATH = Environment.CurrentDirectory + "\\" + "Assets\\Black Cauldron\\Alchemy\\Scripts\\";
        private static readonly string POTIONS_PATH = "Potions\\";
        private static readonly string MODELS_PATH = ALCHEMY_PATH + "Models\\" + POTIONS_PATH;

        private string potionName;

        [MenuItem("Code Generation/Create potion")]
        static void ShowWindow()
        {
            GetWindow<CreatePotionWindow>("Create potion");
        }

        private void OnGUI()
        {
            potionName = GUILayout.TextField(potionName);
            if (GUILayout.Button("Create"))
                Generate(potionName);
        }

        public void Generate(string potionName)
        {
            var potion = ParseName.Parse(potionName);

            var model =
$@"//<auto-generated/>
using UnityEngine;

namespace Ginox.BlackCauldron.Alchemy.Models.Potions
{{
    public class {potion} : APotion
    {{
        public {potion}(Material material) : base(material)
        {{
        }}

        public override string NameKey => nameof({potion});
    }}
}}
";
            ClassFile.SaveClassFile(potion, MODELS_PATH, model);
        }
    }
}
