
//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.Controllers.Ingredients
{
    public class BeaverTailController : AIngredientController
    {
        public BeaverTailController(BeaverTail model) : base(model)
        {
        }
    }
}
