//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.Controllers.Ingredients
{
    public class CoalController : AIngredientController
    {
        public CoalController(Coal model) : base(model)
        {
        }
    }
}
