//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.Controllers.Ingredients
{
    public class GroundHerringSkinController : AIngredientController
    {
        public GroundHerringSkinController(GroundHerringSkin model) : base(model)
        {
        }
    }
}
