//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.Controllers.Ingredients
{
    public class GroundCattailCobController : AIngredientController
    {
        public GroundCattailCobController(GroundCattailCob model) : base(model)
        {
        }
    }
}
