//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.Controllers.Ingredients
{
    public class GroundPineConeController : AIngredientController
    {
        public GroundPineConeController(GroundPineCone model) : base(model)
        {
        }
    }
}
