//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.Controllers.Ingredients
{
    public class GroundBayLeafsController : AIngredientController
    {
        public GroundBayLeafsController(GroundBayLeafs model) : base(model)
        {
        }
    }
}
