//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.Controllers.Ingredients
{
    public class GroundFlyAgaricController : AIngredientController
    {
        public GroundFlyAgaricController(GroundFlyAgaric model) : base(model)
        {
        }
    }
}
