//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.Controllers.Ingredients
{
    public class GroundLicoriceRootController : AIngredientController
    {
        public GroundLicoriceRootController(GroundLicoriceRoot model) : base(model)
        {
        }
    }
}
