//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.Controllers.Ingredients
{
    public class GroundMintController : AIngredientController
    {
        public GroundMintController(GroundMint model) : base(model)
        {
        }
    }
}
