
//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models.Ingredients;

namespace Ginox.BlackCauldron.Alchemy.Controllers.Ingredients
{
    public class MintController : AIngredientController
    {
        public MintController(Mint model) : base(model)
        {
        }
    }
}
