//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models;
using System.Collections.Generic;

namespace Ginox.BlackCauldron.Books.Models
{
    public class BasicHerbsSimpleRemediesGuide : ABook
    {
        public override string NameKey { get; } = nameof(BasicHerbsSimpleRemediesGuide);

        public override List<Recipe> Recipes { get; } = new();
    }
}
