//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Models;
using System.Collections.Generic;

namespace Ginox.BlackCauldron.Books.Models
{
    public class GodsAlchemy : AAlembicBook
    {
        public override string NameKey { get; } = nameof(GodsAlchemy);

        public override List<PotionTransformation> Transformations { get; } = new();
    }
}
