//<auto-generated/>
using Ginox.BlackCauldron.Books.ViewModels;
using Zenject;

namespace Ginox.BlackCauldron.Books.Views
{
    public class BasicHerbsSimpleRemediesGuideView : RecipeBookView
    {
        [Inject]
        private void Init(BasicHerbsSimpleRemediesGuideViewModel viewModel)
        {
            base.Init(viewModel);
        }
    }
}
