//<auto-generated/>

using Ginox.BlackCauldron.Books.ViewModels;
using Zenject;

namespace Ginox.BlackCauldron.Books.Views.Books
{
    public class CombatPotionsView : ABookView
    {
        [Inject]
        private void Init(CombatPotionsViewModel viewModel)
        {
            base.Init(viewModel);
        }
    }
}
