//<auto-generated/>
using Ginox.BlackCauldron.Books.ViewModels;
using Zenject;

namespace Ginox.BlackCauldron.Books.Views.Books
{
    public class TradePotionsView : ABookView
    {
        [Inject]
        private void Init(TradePotionsViewModel viewModel)
        {
            base.Init(viewModel);
        }
    }
}
