//<auto-generated/>
using Ginox.BlackCauldron.Books.Models;

namespace Ginox.BlackCauldron.Books.ViewModels
{
    public class BasicHerbsSimpleRemediesGuideViewModel : ABookViewModel
    {
        public BasicHerbsSimpleRemediesGuideViewModel(BasicHerbsSimpleRemediesGuide model)
        {
            Model = model;
        }
    }
}
