//<auto-generated/>
using Ginox.BlackCauldron.Books.Models;

namespace Ginox.BlackCauldron.Books.ViewModels
{
    public class CombatPotionsViewModel : ABookViewModel
    {
        public CombatPotionsViewModel(CombatPotions model)
        {
            Model = model;
        }
    }
}
