//<auto-generated/>
using Ginox.BlackCauldron.Books.Models;

namespace Ginox.BlackCauldron.Books.ViewModels
{
    public class CourtAlchemySecretsViewModel : AAlembicBookViewModel
    {
        public CourtAlchemySecretsViewModel(CourtAlchemySecrets model)
        {
            Model = model;
        }
    }
}
