//<auto-generated/>
using Ginox.BlackCauldron.Books.Models;

namespace Ginox.BlackCauldron.Books.ViewModels
{
    public class GodsAlchemyViewModel : AAlembicBookViewModel
    {
        public GodsAlchemyViewModel(GodsAlchemy model)
        {
            Model = model;
        }
    }
}
