//<auto-generated/>
using Ginox.BlackCauldron.Books.Models;

namespace Ginox.BlackCauldron.Books.ViewModels
{
    public class PracticeAlchemyViewModel : ABookViewModel
    {
        public PracticeAlchemyViewModel(PracticeAlchemy model)
        {
            Model = model;
        }
    }
}
