//<auto-generated/>
using Ginox.BlackCauldron.Books.Models;

namespace Ginox.BlackCauldron.Books.ViewModels
{
    public class SacredPotionsViewModel : ARecipeBookViewModel
    {
        public SacredPotionsViewModel(SacredPotions model)
        {
            Model = model;
        }
    }
}
