//<auto-generated/>
using Ginox.BlackCauldron.Books.Models;

namespace Ginox.BlackCauldron.Books.ViewModels
{
    public class TradePotionsViewModel : ABookViewModel
    {
        public TradePotionsViewModel(TradePotions model)
        {
            Model = model;
        }
    }
}
