//<auto-generated/>
using Ginox.BlackCauldron.Books.Models;

namespace Ginox.BlackCauldron.Books.ViewModels
{
    public class VillageDoctorsRecipeBookViewModel : ABookViewModel
    {
        public VillageDoctorsRecipeBookViewModel(VillageDoctorsRecipeBook model)
        {
            Model = model;
        }
    }
}
