using Ginox.BlackCauldron.Core.Editor;
using System;
using UnityEditor;
using UnityEngine;

namespace Ginox.BlackCauldron.Books.Editor
{
    public class CreateBookWindow : EditorWindow
    {
        private static readonly string BOOKS_PATH = Environment.CurrentDirectory + "\\" + "Assets\\Black Cauldron\\Books\\Scripts\\";
        private static readonly string BOOK_PATH = "Books\\";
        private static readonly string CONTROLLERS_PATH = BOOKS_PATH + "Controllers\\" + BOOK_PATH;
        private static readonly string VIEWS_PATH = BOOKS_PATH + "Views\\" + BOOK_PATH;

        private string bookName;

        [MenuItem("Code Generation/Create book")]
        static void ShowWindow()
        {
            GetWindow<CreateBookWindow>("Create book");
        }

        private void OnGUI()
        {
            bookName = GUILayout.TextField(bookName);
            if (GUILayout.Button("Create"))
                Generate(bookName);
        }

        public void Generate(string bookName)
        {
            var book = ParseName.Parse(bookName);
            var controllerClassName = $"{book}Controller";
            var viewClassName = $"{book}View";

            var controller =
$@"//<auto-generated/>
namespace Ginox.BlackCauldron.Books.Controllers.Books
{{
    public class {controllerClassName} : ABookController
    {{
    }}
}}
";

            var view =
$@"//<auto-generated/>
using Ginox.BlackCauldron.Books.Controllers.Books;
using Zenject;

namespace Ginox.BlackCauldron.Books.Views.Books
{{
    public class {viewClassName} : ABookView
    {{
        [Inject]
        private void Init({controllerClassName} viewModel)
        {{
            base.Init(viewModel);
        }}
    }}
}}
";
            ClassFile.SaveClassFile(controllerClassName, CONTROLLERS_PATH, controller);
            ClassFile.SaveClassFile(viewClassName, VIEWS_PATH, view);
        }
    }
}
