//<auto-generated/>
namespace Ginox.BlackCauldron.Alchemy.Models.Ingredients
{
    public class GroundBayLeafs : AIngredient
    {
        public override string NameKey => nameof(GroundBayLeafs);
    }
}
