//<auto-generated/>
namespace Ginox.BlackCauldron.Alchemy.Models.Ingredients
{
    public class GroundCattailCob : AIngredient
    {
        public override string NameKey => nameof(GroundCattailCob);
    }
}
