//<auto-generated/>
namespace Ginox.BlackCauldron.Alchemy.Models.Ingredients
{
    public class GroundPineCone : AIngredient
    {
        public override string NameKey => nameof(GroundPineCone);
    }
}
