//<auto-generated/>
namespace Ginox.BlackCauldron.Alchemy.Models.Ingredients
{
    public class GroundFlyAgaric : AIngredient
    {
        public override string NameKey => nameof(GroundFlyAgaric);
    }
}
