//<auto-generated/>
namespace Ginox.BlackCauldron.Alchemy.Models.Ingredients
{
    public class GroundHerringSkin : AIngredient
    {
        public override string NameKey => nameof(GroundHerringSkin);
    }
}
