//<auto-generated/>
namespace Ginox.BlackCauldron.Alchemy.Models.Ingredients
{
    public class GroundLicoriceRoot : AIngredient
    {
        public override string NameKey => nameof(GroundLicoriceRoot);
    }
}
