//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.ViewModels.Ingredients;
using Ginox.BlackCauldron.Alchemy.ViewModels.Tools;
using Ginox.BlackCauldron.Alchemy.Views.Tools;
using Zenject;

namespace Ginox.BlackCauldron.Alchemy.Views.Ingredients
{
    public class CoalView : AIngredientView, IMortarInteractable, IAlembicFirepitInteract
    {
        [Inject]
        private void Init(CoalViewModel controller)
        {
            base.Init(controller);
        }

        public void Interact(MortarViewModel controller)
        {
            controller.PutIn(this);
        }

        public void Interact(AlembicViewModel alembicController)
        {
            if (alembicController.TryAddFuel())
                Destroy(gameObject);
        }
    }
}
