//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Controllers.Ingredients;
using Zenject;

namespace Ginox.BlackCauldron.Alchemy.Views.Ingredients
{
    public class GroundFlyAgaricView : AIngredientView
    {
        [Inject]
        private void Init(GroundFlyAgaricController controller)
        {
            base.Init(controller);
        }
    }
}
