
//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Controllers.Ingredients;
using Ginox.BlackCauldron.Alchemy.Controllers.Tools;
using Ginox.BlackCauldron.Alchemy.Views.Tools;
using Zenject;

namespace Ginox.BlackCauldron.Alchemy.Views.Ingredients
{
    public class MintView : AIngredientView, IMortarInteractable
    {
        [Inject]
        private void Init(MintController controller)
        {
            base.Init(controller);
        }

        public void Interact(MortarController controller)
        {
            controller.PutIn(this);
        }
    }
}
