
//<auto-generated/>
using Ginox.BlackCauldron.Alchemy.Controllers.Ingredients;
using Zenject;

namespace Ginox.BlackCauldron.Alchemy.Views.Ingredients
{
    public class MintView : AIngredientView
    {
        [Inject]
        private void Init(MintController controller)
        {
            base.Init(controller);
        }
    }
}
